"""empty message

Revision ID: 9366cacd3db7
Revises: 
Create Date: 2021-07-21 14:47:24.450572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9366cacd3db7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_name', sa.String(length=200), nullable=False),
    sa.Column('order_list', sa.Text(), nullable=False),
    sa.Column('ordered_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    # ### end Alembic commands ###
